### ISSUE TITLE
CX App is not setup to support Ubuntu Bionic. 

### ISSUE THREAD

**Issue by kgividen** [MicroFocus/CX#24]
This causes an issue when doing docker compose where python3.5 is not found.  It also causes other errors since the version of nodesource and other things don't yet support bionic.  Everything should probably be updated for that.

However, to work around this currently you can change the "FROM ubuntu" to "FROM ubuntu:16.04" in the docker file so it specifies a correct version (in this case Xenial).  There's an argument to be made this should be the default.  Otherwise, CXAPP is at the whim of when new releases come out.

**Comment by RikPeters** [comment]
hi @kgividen ,
if you look at the following commit you will see this is already done:
https://github.com/MicroFocus/CX/commit/bd7a8be448e669561a418d235ab77aac152a4e11

If you still are experiencing issues please let us know.

Thanks,
Rik
